### ISSUE TITLE
Checkout hangs

### ISSUE THREAD

**Issue by ohlzon** [hedqvist/SwishWoocommerce#1]
After activating the plugin and enabling the Swish payment gateway the checkout process hangs at load, it stays grayed out/spinner visible and the Place order button never becomes active.

Additionally, I get the following error when switching themes, removing plugins:
_Warning: Cannot modify header information - headers already sent by (output started at /Users/ohlzon/dev/testsite/wp-content/plugins/woocommerce-swish/woocommerce-swish.php:1) in /Users/ohlzon/dev/testsite/wp-includes/pluggable.php on line 1178_

**Comment by hedqvist** [comment]
Solved
