### ISSUE TITLE
Licens

### ISSUE THREAD

**Issue by oleander** [hedqvist/SwishWoocommerce#7]
Vilken licens ligger mjukvaran under?

**Comment by hedqvist** [comment]
GPLv3 - Läs gärna mer på http://www.gnu.org/licenses/gpl-3.0.html

**Comment by oleander** [comment]
Super. Kan du lägga till en LICENSE-fil i repon som bekräftar detta?

**Comment by hedqvist** [comment]
Jag ordnar detta imorgon. Får man fråga varför du ville veta vilken licens licens det ligger under?

**Comment by oleander** [comment]
Annars betyder de att jag som användare måste fråga dig som upphovsinnehavare om lov för att använda koden.

-- 
Linus Oleander

På 11 oktober 2015 till 20:37:16, Christopher Hedqvist (notifications@github.com) skrev:

Jag ordnar detta imorgon. Får man fråga varför du ville veta vilken licens licens det ligger under?

**Comment by hedqvist** [comment]
Jag förstår, laddar upp filen så snart jag kan.

Du hittar även koden på redlight.se/swish

Detta repo kommer förmodligen bli privat, då vi påbörjat en ny version mot swish's api.

MVH 
Christopher Hedqvist 
+46(0)73-9 12 07 27
christopher.hedqvist@redlight.se
